[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 10_000
verbosity = 3

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://sepolia.etherscan.io/" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
bracket_spacing = true
line_length = 80
wrap_comments = true
tab_width = 2
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config